/**
 * 
 */
const data = `[{"id":1,"first_name":"Mayor","last_name":"Colecrough","email":"mcolecrough0@dot.gov","gender":"Male","salary":9252},
{"id":2,"first_name":"Rosette","last_name":"Douthwaite","email":"rdouthwaite1@taobao.com","gender":"Female","salary":4737},
{"id":3,"first_name":"Sonja","last_name":"Kohrs","email":"skohrs2@eventbrite.com","gender":"Female","salary":5009},
{"id":4,"first_name":"Jarid","last_name":"McAloren","email":"jmcaloren3@irs.gov","gender":"Male","salary":3914},
{"id":5,"first_name":"Hendrik","last_name":"Ellerker","email":"hellerker4@nytimes.com","gender":"Male","salary":9374},
{"id":6,"first_name":"Babb","last_name":"Buist","email":"bbuist5@comcast.net","gender":"Female","salary":6214},
{"id":7,"first_name":"Marika","last_name":"Petford","email":"mpetford6@bigcartel.com","gender":"Female","salary":6753},
{"id":8,"first_name":"Darya","last_name":"Laterza","email":"dlaterza7@yelp.com","gender":"Female","salary":6730},
{"id":9,"first_name":"Tad","last_name":"Balle","email":"tballe8@samsung.com","gender":"Male","salary":7053},
{"id":10,"first_name":"Marlow","last_name":"Slym","email":"mslym9@flavors.me","gender":"Male","salary":3807},
{"id":11,"first_name":"Raleigh","last_name":"Lates","email":"rlatesa@usgs.gov","gender":"Male","salary":3657},
{"id":12,"first_name":"Mackenzie","last_name":"Copozio","email":"mcopoziob@boston.com","gender":"Male","salary":7735},
{"id":13,"first_name":"Melisande","last_name":"Vogt","email":"mvogtc@ocn.ne.jp","gender":"Female","salary":8058},
{"id":14,"first_name":"Zola","last_name":"Adolf","email":"zadolfd@moonfruit.com","gender":"Female","salary":8786},
{"id":15,"first_name":"Jerald","last_name":"Hegdonne","email":"jhegdonnee@360.cn","gender":"Male","salary":5451},
{"id":16,"first_name":"Penny","last_name":"Mingaye","email":"pmingayef@webnode.com","gender":"Male","salary":7169},
{"id":17,"first_name":"Dreddy","last_name":"Berendsen","email":"dberendseng@pagesperso-orange.fr","gender":"Female","salary":4918},
{"id":18,"first_name":"Ninon","last_name":"Berriman","email":"nberrimanh@bing.com","gender":"Female","salary":3040},
{"id":19,"first_name":"Tabina","last_name":"Saladino","email":"tsaladinoi@hc360.com","gender":"Female","salary":9926},
{"id":20,"first_name":"Cart","last_name":"Chalke","email":"cchalkej@apple.com","gender":"Male","salary":6449}]`;